<?php

// include_once(drupal_get_path('module', 'scholarregister') . '/scholarregister.pages.inc');

/**
 * hook strongarm
 */
function unt_scholar_strongarm_alter(&$items) {
  watchdog('unt_scholar', 'strongarm items look like @items', array('@items' => var_dump($items)));
  
  // the default project site theme
  $items['openscholar_vsite_default_theme']->value = 'scholar-unt_stripy';

  // list of themes, one will be randomly selected as default for new sites created
  $items['openscholar_selected_themes']->value = array('scholar-unt_stripy');

  // setting determines if a non admin user can create multiple sites
  $items['scholar_create_multiple_sites']->value = 0;
}

function unt_scholar_menu_alter(&$items) {
  //alter the page callback function
  $items['site/register']['access callback'] = 'unt_scholar_form_access';  //change the callback function
}

function unt_scholar_form_access() {
  global $user;
  if(in_array('authenticated user', $user->roles)) {
    return true;
  }
  else {
    return false;
  }
}

