<?php

// include_once(drupal_get_path('module', 'scholarregister') . '/scholarregister.pages.inc');

/**
 * hook strongarm
 */
function scholar_strongarm(){
  $conf = array();
  
  // the default project site theme
  $conf['openscholar_vsite_default_theme'] = 'scholar-unt_stripy';

  // list of themes, one will be randomly selected as default for new sites created
  $conf['openscholar_selected_themes'] = array('scholar-unt_stripy');

  // setting determines if a non admin user can create multiple sites
  $conf['scholar_create_multiple_sites'] = 0;
}

